# Generated by Django 5.2.1 on 2025-11-26 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='currentbalence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blance', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('expense_type', models.CharField(choices=[('credit', 'credit'), ('debit', 'debit')], max_length=10)),
                ('discription', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('balence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traker.currentbalence')),
            ],
        ),
    ]
