# Generated by Django 5.2.1 on 2025-11-29 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentbalence',
            old_name='blance',
            new_name='balence',
        ),
    ]
